version: "3"
services:
  mysql-server:
    image: mysql:8.0.35
    container_name: mysql-server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Genzii12345@@
    networks:
      - genzii
      
  genzii-backend:
    build:
      context: ./genzii-backend-laravel
      dockerfile: ./Dockerfile
    container_name: genzii-backend
    working_dir: /var/www/html
    volumes:
      - ./images:/var/www/html/storage/app
    ports:
      - "8000:80"
    networks:
      - genzii

  genzii-frontend:
    build:
      context: ./genzii-frontend-reactjs
      dockerfile: ./Dockerfile
    container_name: genzii-frontend
    ports:
      - "80:80"
    networks:
      - genzii

networks:
  genzii:
  
    

  

  