version: "3"
services:
  mysql-server:
    image: mysql:8.0.35
    container_name: mysql-server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Genzii12345@@
      
  genzii-backend:
    links:
      - mysql-server
    build:
      context: ./genzii-backend-laravel
      dockerfile: ./Dockerfile
    container_name: genzii-backend
    working_dir: /var/www/html
    ports:
      - "8000:80"

  genzii-image-server:
    build:
      context: ./genzii-image-server
      dockerfile: ./Dockerfile
    container_name: genzii-image-server
    working_dir: /var/www/html
    ports:
      - "9000:80"

  genzii-frontend:
    build:
      context: ./genzii-frontend-reactjs
      dockerfile: ./Dockerfile
    container_name: genzii-frontend
    ports:
      - "80:80"
    
  
    

  

  