FROM mysql:8.0.35

# COPY genzii_db_1.sql /docker-entrypoint-initdb.d/

# ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

# RUN ["docker-entrypoint.sh", "mysqld", "--init-file", "/docker-entrypoint-initdb.d/genzii_db_1.sql"]

